name: PronounsAdvanced
version: '${version}'
main: net.cufufy.pronouns.paper.ProNounsPaper
api-version: 1.21
authors: [cufufy]
website: https://cufufy.net
softdepend: [PlaceholderAPI]

# commands and permissions are defined at runtime
